easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'description'
                    - 'filename'
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image'}


