easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'type'
                    - 'description'
                    - 'filename'
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            form:
                fields:
                    - 'title'
                    - { property: 'type', type: 'choice', type_options: { choices: {'frame': 'frame', 'accessories': 'accessories', 'shelf': 'shelf', 'mirror': 'mirror', 'emblem': 'emblem', 'lamp': 'lamp', 'clock': 'clock'}}}
                    - { property: 'description', type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'content'
                    - 'filename'
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

            form:
                fields:
                    - 'title'
                    - { property: 'content', type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }

