vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
